name: tde3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^4.0.3
  flutter:
    sdk: flutter
  workmanager: ^0.5.2
  logger: ^2.3.0
  permission_handler: ^11.3.1
  http: ^0.13.3
  flutter_local_notifications: ^9.1.2
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
